### ISSUE TITLE
Magnetic Events don't work in Cardboard SDK 0.6

### ISSUE THREAD

**Issue by HAZARDU5** [JScott/cardboard-controls#18] opened 2016-01-23 22:00 UTC
Cardboard SDK was recently updated to v0.6 and it seems like the magnetic events (`trigger.OnDown`, `trigger.OnUp` and `trigger.OnClick`) no longer fire on the actual device in CardboardControl v3.4. Using the raw `Cardboard.SDK.Triggered` invocation from the SDK seems to work correctly though. Debug controls for these work correctly in the Unity editor when pressing the appropriate key on the keyboard.

It'd be great to get this working as we're trying to develop a space shooter and need to be able to hold down the magnetic control to activate forward thrusters for our ship. Currently we have to use 'clicks' to toggle the thrusters on and off which isn't as intuitive.

**Comment by JScott** [comment] 2016-01-24 02:12
I'm updating to v0.6 now and I'm getting magnet controls triggering properly. I should have a new release up soon that you can try out and see if it fixes your problem.

**Comment by JScott** [comment] 2016-01-24 02:54
https://github.com/JScott/cardboard-controls/releases/tag/v3.5 let me know if this fixes your problems.

**Comment by HAZARDU5** [comment] 2016-01-24 04:00
Just tried it out now - I'm getting the following error in the demoscene now:

```
NullReferenceException: Object reference not set to an instance of an object
ExampleCharacterController.CardboardGazeChange (System.Object sender) (at Assets/CardboardControl/DemoScene/ExampleCharacterController.cs:83)
CardboardControlGaze.ReportGazeChange () (at Assets/CardboardControl/Scripts/CardboardControlGaze.cs:60)
CardboardControlGaze.CheckGaze () (at Assets/CardboardControl/Scripts/CardboardControlGaze.cs:41)
CardboardControlGaze.Update () (at Assets/CardboardControl/Scripts/CardboardControlGaze.cs:37)
```

Same problem when attempting to do `cardboard.reticle.Hide();` in my own scenes.

**Comment by HAZARDU5** [comment] 2016-01-24 04:17
Additionally, still getting the same problem with `trigger.OnDown`, `trigger.OnUp` and `trigger.OnClick` not working on actual Google Cardboard hardware.

**Comment by JScott** [comment] 2016-01-24 05:34
Did you remove the old scripts and replace them fresh with the latest unitypackage? I can't reproduce this problem when I:

* start a new, empty 3D project
* import the unitypackage
* import the prefabs mentioned in the README
* build and run
* click the trigger to produce a vibration, the default behaviour

That's with Unity 5.2.3f1 on a Nexus 5X and the demo scene builds and runs as well.

Unity has problems realizing when scripts are updated from a unitypackage which I suspect might be causing issues. When I updated the Cardboard SDK I've taken to just deleting the Cardboard and Plugins folder first, for example.

**Comment by HAZARDU5** [comment] 2016-01-24 06:13
Deleting them and adding them again seems to have fixed it. Getting the OnDown and OnUp events triggering sometimes, but this is not always consistent. It could be a problem with my device though!

**Comment by JScott** [comment] 2016-01-24 07:26
Glad to hear that was the main issue. I get worried that I've gone crazy and broke everything whenever that happens D:

As for the inconsistency, that is the unfortunate nature of the magnet controls. My job would be so much simpler if I only had to support the touch events of the v2. I do have some debug tools to help you dig into it though if you'd like to give it a shot.

If you enable "Print Debug Info" from the `CardboardControlManager`, the magnet data parser will dump out the magnitude, ratio over a time window, ratio delta, if the device is stable enough to start using the magnetometer data, and what state the device thinks the magnet is in. If you grab that info from `adb logcat` then you can correlate it to the logic which is more or less:

* the device is stable when the magnetometer reads high enough (>200 on Android), the ratio is within a low threshold (1+/-0.001), and the delta is low enough (<2) to indicate a plateau
* the device stays stable until the magnetometer no longer reads high enough
* the magnet state is negative from 0.8 to 0.97 and positive from 1.03 to 1.2
* positive and negative don't indicate up or down since magnet direction doesn't correlate with raw data reading direction (unfortunately)

Usually what happens is the magnet isn't getting over one of those thresholds. Sometimes moving the device closer to the magnet in your casing by half an inch can make all the difference. You may be able to get it working by tweaking those numbers at the top of `ParsedMagnetData.cs` as well.

If you do fiddle with the numbers and get it working, please let me know. It may be worth tweaking the base values because it's a balancing act between being too permissive and getting false readings or being too restrictive and not detecting movement. It's so much easier with the v2!

**Comment by JScott** [comment] 2016-01-24 07:33
I'm going to close this specific issue. We solved the problem at hand and I'm going to add something to the README so people are aware that they should delete previous scripts to update.

If you do want to reach out to talk thresholds, email and [gitter](https://gitter.im/JScott/cardboard-controls) (which emails me) are both good. Or just drop another issue, whichever works for you.

**Closed by JScott** 2016-01-24 07:33 UTC
Labels: bug

**Comment by HAZARDU5** [comment] 2016-01-24 20:57
No worries - thanks for the tips :-)

I'm getting a Cardboard V2 this week so I may end up switching to that control scheme and just use the built in Cardboard SDK events for V1 devices that use the magnetometer.
